theme: jekyll-theme-cayman
git add _config.yml
git commit -m "Add Jekyll theme to _config.yml"
git push origin main 

title: Veronica Vazquez Portfolio
description: This is my personal blog built with Jekyll
theme: jekyll-theme-cayman
url: https://github.com/verovaz/Portofolio-Projects.git
baseurl: /<verovaz> 
